config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "debts#index"
  resources :debts, only: [:index, :new, :create]

  get 'debts/transition_balance', to: 'debts#transition_balance'
  get 'debts/transition_IncDec', to: 'debts#transition_IncDec'
  get 'debts/transition_InOut', to: 'debts#transition_InOut'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank.rb
class Bank < ActiveHash::Base
  self.data = [
      {id: 1, name: '三菱UFJ銀行'}, {id: 2, name: 'みずほ銀行'}, {id: 3, name: '日本政策金融公庫'}
  ]
end

app/models/debt.rb
class Debt < ApplicationRecord
  belongs_to_active_hash :bank
  belongs_to_active_hash :debt
  belongs_to_active_hash :repayment_cycle
end

app/models/debt_type.rb
class Debt_type < ActiveHash::Base
  self.data = [
      {id: 1, name: '証書借入'}, {id: 2, name: '手形借入'}, {id: 3, name: '社債'}
  ]
end

app/models/repayment_cycle.rb
class Repayment_cycle < ActiveHash::Base
  self.data = [
      {id: 1, name: '毎月', cycle: '1'}, {id: 2, name: '半年に1回', cycle: '6'}, {id: 3, name: '1年に1回', cycle: '12'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/debts_controller.rb
class DebtsController < ApplicationController

  def index
  end

  def new
  end

  def create
  end

  def transition_balance
  end

  def transition_IncDec
  end

  def transition_InOut
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/debts_helper.rb
module DebtsHelper
end

app/views/debts/_side-bar.html.haml
.side-bar
  .side-bar__top
    .side-bar__top__username taka
    .side-bar__top__box
      = link_to "#" do
        .side-bar__top__box__create 事業所の新規作成
      = link_to "#" do
        .side-bar__top__box__login_logout ログアウト
  .side-bar__list
    = link_to "#" do
      .side-bar__list__item AAA社
    = link_to "#" do
      .side-bar__list__item BBB社
    = link_to "#" do
      .side-bar__list__item CCC社

app/views/debts/index.html.haml
.wrapper
  = render partial: "side-bar"
  .main
    .main__top
      .main__top__company_name AAA社
      .main__top__box
        = link_to new_debt_path do
          .main__top__box__create 借入金登録
        = link_to debts_transition_balance_path do
          .main__top__box__index 借入金推移
        = link_to root_path do
          .main__top__box__index 借入金一覧
    .main__contents
      %table.main__contens__table
        %tr.main__contents__table__head
          %th.main__contents__table__head__cell タイトル
          %th.main__contents__table__head__cell 金融機関名
          %th.main__contents__table__head__cell 借入日
          %th.main__contents__table__head__cell 当初借入額
          %th.main__contents__table__head__cell 残高
          %th.main__contents__table__head__cell 利率
        %tr.main__contents__table__record
          %td
            = link_to "#" do
              .main__contents__table__record__cell 新規借入A
          %td.main__contents__table__record__cell みずほ銀行
          %td.main__contents__table__record__cell 2020/4/1
          %td.main__contents__table__record__cell 50,000,000
          %td.main__contents__table__record__cell 20,000,000
          %td.main__contents__table__record__cell 2.000%
        %tr.main__contents__table__record
          %td
            = link_to "#" do
              .main__contents__table__record__cell 新規借入B
          %td.main__contents__table__record__cell みずほ銀行
          %td.main__contents__table__record__cell 2020/4/1
          %td.main__contents__table__record__cell 50,000,000
          %td.main__contents__table__record__cell 20,000,000
          %td.main__contents__table__record__cell 2.000%
        %tr.main__contents__table__record
          %td
            = link_to "#" do
              .main__contents__table__record__cell 新規借入B
          %td.main__contents__table__record__cell みずほ銀行
          %td.main__contents__table__record__cell 2020/4/1
          %td.main__contents__table__record__cell 50,000,000
          %td.main__contents__table__record__cell 20,000,000
          %td.main__contents__table__record__cell 2.000%
        %tr.main__contents__table__record
          %td
            = link_to "#" do
              .main__contents__table__record__cell 新規借入A
          %td.main__contents__table__record__cell みずほ銀行
          %td.main__contents__table__record__cell 2020/4/1
          %td.main__contents__table__record__cell 50,000,000
          %td.main__contents__table__record__cell 20,000,000
          %td.main__contents__table__record__cell 2.000%
        %tr.main__contents__table__record
          %td
            = link_to "#" do
              .main__contents__table__record__cell 新規借入B
          %td.main__contents__table__record__cell みずほ銀行
          %td.main__contents__table__record__cell 2020/4/1
          %td.main__contents__table__record__cell 50,000,000
          %td.main__contents__table__record__cell 20,000,000
          %td.main__contents__table__record__cell 2.000%
        %tr.main__contents__table__record
          %td
            = link_to "#" do
              .main__contents__table__record__cell 新規借入B
          %td.main__contents__table__record__cell みずほ銀行
          %td.main__contents__table__record__cell 2020/4/1
          %td.main__contents__table__record__cell 50,000,000
          %td.main__contents__table__record__cell 20,000,000
          %td.main__contents__table__record__cell 2.000%
        %tr.main__contents__table__record
          %td
            = link_to "#" do
              .main__contents__table__record__cell 新規借入A
          %td.main__contents__table__record__cell みずほ銀行
          %td.main__contents__table__record__cell 2020/4/1
          %td.main__contents__table__record__cell 50,000,000
          %td.main__contents__table__record__cell 20,000,000
          %td.main__contents__table__record__cell 2.000%
        %tr.main__contents__table__record
          %td
            = link_to "#" do
              .main__contents__table__record__cell 新規借入B
          %td.main__contents__table__record__cell みずほ銀行
          %td.main__contents__table__record__cell 2020/4/1
          %td.main__contents__table__record__cell 50,000,000
          %td.main__contents__table__record__cell 20,000,000
          %td.main__contents__table__record__cell 2.000%
        %tr.main__contents__table__record
          %td
            = link_to "#" do
              .main__contents__table__record__cell 新規借入B
          %td.main__contents__table__record__cell みずほ銀行
          %td.main__contents__table__record__cell 2020/4/1
          %td.main__contents__table__record__cell 50,000,000
          %td.main__contents__table__record__cell 20,000,000
          %td.main__contents__table__record__cell 2.000%
        %tr.main__contents__table__record
          %td
            = link_to "#" do
              .main__contents__table__record__cell 新規借入A
          %td.main__contents__table__record__cell みずほ銀行
          %td.main__contents__table__record__cell 2020/4/1
          %td.main__contents__table__record__cell 50,000,000
          %td.main__contents__table__record__cell 20,000,000
          %td.main__contents__table__record__cell 2.000%
        %tr.main__contents__table__record
          %td
            = link_to "#" do
              .main__contents__table__record__cell 新規借入B
          %td.main__contents__table__record__cell みずほ銀行
          %td.main__contents__table__record__cell 2020/4/1
          %td.main__contents__table__record__cell 50,000,000
          %td.main__contents__table__record__cell 20,000,000
          %td.main__contents__table__record__cell 2.000%
        %tr.main__contents__table__record
          %td
            = link_to "#" do
              .main__contents__table__record__cell 新規借入B
          %td.main__contents__table__record__cell みずほ銀行
          %td.main__contents__table__record__cell 2020/4/1
          %td.main__contents__table__record__cell 50,000,000
          %td.main__contents__table__record__cell 20,000,000
          %td.main__contents__table__record__cell 2.000%
        %tr.main__contents__table__record
          %td
            = link_to "#" do
              .main__contents__table__record__cell 新規借入A
          %td.main__contents__table__record__cell みずほ銀行
          %td.main__contents__table__record__cell 2020/4/1
          %td.main__contents__table__record__cell 50,000,000
          %td.main__contents__table__record__cell 20,000,000
          %td.main__contents__table__record__cell 2.000%
        %tr.main__contents__table__record
          %td
            = link_to "#" do
              .main__contents__table__record__cell 新規借入B
          %td.main__contents__table__record__cell みずほ銀行
          %td.main__contents__table__record__cell 2020/4/1
          %td.main__contents__table__record__cell 50,000,000
          %td.main__contents__table__record__cell 20,000,000
          %td.main__contents__table__record__cell 2.000%
        %tr.main__contents__table__record
          %td
            = link_to "#" do
              .main__contents__table__record__cell 新規借入B
          %td.main__contents__table__record__cell みずほ銀行
          %td.main__contents__table__record__cell 2020/4/1
          %td.main__contents__table__record__cell 50,000,000
          %td.main__contents__table__record__cell 20,000,000
          %td.main__contents__table__record__cell 2.000%
        %tr.main__contents__table__record--total
          %td.main__contents__table__record__cell 合計
          %td.main__contents__table__record__cell 
          %td.main__contents__table__record__cell 
          %td.main__contents__table__record__cell 
          %td.main__contents__table__record__cell 200,000,000
          %td.main__contents__table__record__cell 
      

app/views/debts/new.html.haml
.wrapper
  = render partial: "side-bar"
  .main
    .main__top
      .main__top__company_name AAA社
      .main__top__box
        = link_to new_debt_path do
          .main__top__box__create 借入金登録
        = link_to debts_transition_balance_path do
          .main__top__box__index 借入金推移
        = link_to root_path do
          .main__top__box__index 借入金一覧
    .main__contents
      = form_with model:@debt, url: new_debt_path, class: 'main__contents__form', local: true do |f|
        .main__contents__form__field
          = f.label "タイトル", class:"main__contents__form__field__label"
          %span.main__contents__form__field__require 必須
          %br/
          = f.text_field :title, autofocus: true, class:"main__contents__form__field__input--one"
        .main__contents__form__field
          = f.label "金融機関", class:"main__contents__form__field__label"
          %span.main__contents__form__field__require 必須
          %br/
          = f.collection_select :bank_id, Bank.all, :id, :name, {include_blank: true},{class:"main__contents__form__field__input--select"}
        .main__contents__form__field
          = f.label "当初元金", class:"main__contents__form__field__label"
          %span.main__contents__form__field__require 必須
          %br/
          = f.text_field :principal, class:"main__contents__form__field__input--one"
        .main__contents__form__field
          = f.label "借入日", class:"main__contents__form__field__label"
          %span.main__contents__form__field__require 必須
          %br/
          != sprintf(f.date_select(:borrowing_day, use_month_numbers: true,start_year: 2000, end_year: (Time.now.year - 0), include_blank: true, with_css_classes:"",date_separator:'%s'),'年','月')+'日'
        .main__contents__form__field
          = f.label "返済期限", class:"main__contents__form__field__label"
          %span.main__contents__form__field__optional 任意
          %br/
          != sprintf(f.date_select(:repayment_deadline, use_month_numbers: true,start_year: 2000, end_year: (Time.now.year - 0), include_blank: true, with_css_classes:"",date_separator:'%s'),'年','月')+'日'
        .main__contents__form__field
          = f.label "借入金種類", class:"main__contents__form__field__label"
          %span.main__contents__form__field__require 必須
          %br/
          = f.collection_select :bank_id, Debt_type.all, :id, :name, {include_blank: true},{class:"main__contents__form__field__input--select"}
        .main__contents__form__field
          = f.label "返済開始日", class:"main__contents__form__field__label"
          %span.main__contents__form__field__require 必須
          %br/
          != sprintf(f.date_select(:repayment_start_day, use_month_numbers: true,start_year: 2000, end_year: (Time.now.year - 0), include_blank: true, with_css_classes:"",date_separator:'%s'),'年','月')+'日'
        .main__contents__form__field
          = f.label "返済回数", class:"main__contents__form__field__label"
          %span.main__contents__form__field__require 必須
          %br/
          = f.text_field :number_of_repayment, class:"main__contents__form__field__input--one"
        .main__contents__form__field
          = f.label "１回目返済金額", class:"main__contents__form__field__label"
          %span.main__contents__form__field__require 必須
          %br/
          = f.text_field :repayment_first, class:"main__contents__form__field__input--one"
        .main__contents__form__field
          = f.label "２回目以降返済金額", class:"main__contents__form__field__label"
          %span.main__contents__form__field__require 必須
          %br/
          = f.text_field :repayment_second, class:"main__contents__form__field__input--one"
        .main__contents__form__field
          = f.label "返済サイクル", class:"main__contents__form__field__label"
          %span.main__contents__form__field__require 必須
          %br/
          = f.collection_select :bank_id, Repayment_cycle.all, :id, :name, {include_blank: true},{class:"main__contents__form__field__input--select"}
        .main__contents__form__field
          = f.label "利率", class:"main__contents__form__field__label"
          %span.main__contents__form__field__require 必須
          %br/
          = f.text_field :interrest_rate, class:"main__contents__form__field__input--one"
        .main__contents__form__submit
        = f.submit "登録する",class:"main__contents__form__submit__btn"

app/views/debts/transition_InOut.html.haml
.wrapper
  = render partial: "side-bar"
  .main
    .main__top
      .main__top__company_name AAA社
      .main__top__box
        = link_to new_debt_path do
          .main__top__box__create 借入金登録
        = link_to debts_transition_balance_path do
          .main__top__box__index 借入金推移
        = link_to root_path do
          .main__top__box__index 借入金一覧
    .main__contents
      .main__contents__nav
        = link_to debts_transition_balance_path do
          .main__contents__nav__link 残高推移
        = link_to debts_transition_IncDec_path do
          .main__contents__nav__link 増減
        = link_to debts_transition_InOut_path do
          .main__contents__nav__link 収支
      %table.main__contens__table
        %tr.main__contents__table__head
          %th.main__contents__table__head__cell
          %th.main__contents__table__head__cell 2020-04
          %th.main__contents__table__head__cell 2020-05
          %th.main__contents__table__head__cell 2020-06
          %th.main__contents__table__head__cell 2020-07
          %th.main__contents__table__head__cell 2020-08
          %th.main__contents__table__head__cell 2020-09
          %th.main__contents__table__head__cell 2020-10
          %th.main__contents__table__head__cell 2020-11
          %th.main__contents__table__head__cell 2021-12
          %th.main__contents__table__head__cell 2022-01
          %th.main__contents__table__head__cell 2023-02
          %th.main__contents__table__head__cell 2024-03
        %tr.main__contents__table__record
          %td.main__contents__table__record__cell--sticky 収入（新規借入）
          %td.main__contents__table__record__cell 50,000
          %td.main__contents__table__record__cell 
          %td.main__contents__table__record__cell 
          %td.main__contents__table__record__cell 
          %td.main__contents__table__record__cell 
          %td.main__contents__table__record__cell 
          %td.main__contents__table__record__cell 
          %td.main__contents__table__record__cell 
          %td.main__contents__table__record__cell 
          %td.main__contents__table__record__cell 
          %td.main__contents__table__record__cell 
          %td.main__contents__table__record__cell 
        %tr.main__contents__table__record
          %td.main__contents__table__record__cell--sticky 支出（元金返済）
          %td.main__contents__table__record__cell 
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
        %tr.main__contents__table__record
          %td.main__contents__table__record__cell--sticky 利息
          %td.main__contents__table__record__cell 
          %td.main__contents__table__record__cell ▲200
          %td.main__contents__table__record__cell ▲200
          %td.main__contents__table__record__cell ▲200
          %td.main__contents__table__record__cell ▲200
          %td.main__contents__table__record__cell ▲200
          %td.main__contents__table__record__cell ▲200
          %td.main__contents__table__record__cell ▲200
          %td.main__contents__table__record__cell ▲200
          %td.main__contents__table__record__cell ▲200
          %td.main__contents__table__record__cell ▲200
          %td.main__contents__table__record__cell ▲200
        %tr.main__contents__table__record--total
          %td.main__contents__table__record__cell--sticky 収支
          %td.main__contents__table__record__cell 50,000
          %td.main__contents__table__record__cell ▲2,200
          %td.main__contents__table__record__cell ▲2,200
          %td.main__contents__table__record__cell ▲2,200
          %td.main__contents__table__record__cell ▲2,200
          %td.main__contents__table__record__cell ▲2,200
          %td.main__contents__table__record__cell ▲2,200
          %td.main__contents__table__record__cell ▲2,200
          %td.main__contents__table__record__cell ▲2,200
          %td.main__contents__table__record__cell ▲2,200
          %td.main__contents__table__record__cell ▲2,200
          %td.main__contents__table__record__cell ▲2,200 

app/views/debts/transition_IncDec.html.haml
.wrapper
  = render partial: "side-bar"
  .main
    .main__top
      .main__top__company_name AAA社
      .main__top__box
        = link_to new_debt_path do
          .main__top__box__create 借入金登録
        = link_to debts_transition_balance_path do
          .main__top__box__index 借入金推移
        = link_to root_path do
          .main__top__box__index 借入金一覧
    .main__contents
      .main__contents__nav
        = link_to debts_transition_balance_path do
          .main__contents__nav__link 残高推移
        = link_to debts_transition_IncDec_path do
          .main__contents__nav__link 増減
        = link_to debts_transition_InOut_path do
          .main__contents__nav__link 収支
      %table.main__contens__table
        %tr.main__contents__table__head
          %th.main__contents__table__head__cell
          %th.main__contents__table__head__cell
          %th.main__contents__table__head__cell 2020-04
          %th.main__contents__table__head__cell 2020-05
          %th.main__contents__table__head__cell 2020-06
          %th.main__contents__table__head__cell 2020-07
          %th.main__contents__table__head__cell 2020-08
          %th.main__contents__table__head__cell 2020-09
          %th.main__contents__table__head__cell 2020-10
          %th.main__contents__table__head__cell 2020-11
          %th.main__contents__table__head__cell 2021-12
          %th.main__contents__table__head__cell 2022-01
          %th.main__contents__table__head__cell 2023-02
          %th.main__contents__table__head__cell 2024-03
        %tr.main__contents__table__record
          %td.main__contents__table__record__cell--sticky みずほ銀行
          %td.main__contents__table__record__cell--button 詳細
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
        %tr.main__contents__table__record#record_1
          %td.main__contents__table__record__cell--sticky みずほ銀行
          %td.main__contents__table__record__cell--button 詳細
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
        %tr.main__contents__table__record#record_1
          %td.main__contents__table__record__cell--sticky みずほ銀行
          %td.main__contents__table__record__cell--button 詳細
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
          %td.main__contents__table__record__cell ▲2,000
    

app/views/debts/transition_balance.html.haml
.wrapper
  = render partial: "side-bar"
  .main
    .main__top
      .main__top__company_name AAA社
      .main__top__box
        = link_to new_debt_path do
          .main__top__box__create 借入金登録
        = link_to debts_transition_balance_path do
          .main__top__box__index 借入金推移
        = link_to root_path do
          .main__top__box__index 借入金一覧
    .main__contents
      .main__contents__nav
        = link_to debts_transition_balance_path do
          .main__contents__nav__link 残高推移
        = link_to debts_transition_IncDec_path do
          .main__contents__nav__link 増減
        = link_to debts_transition_InOut_path do
          .main__contents__nav__link 収支
      %table.main__contens__table
        %tr.main__contents__table__head
          %th.main__contents__table__head__cell
          %th.main__contents__table__head__cell
          %th.main__contents__table__head__cell 2020-04
          %th.main__contents__table__head__cell 2020-05
          %th.main__contents__table__head__cell 2020-06
          %th.main__contents__table__head__cell 2020-07
          %th.main__contents__table__head__cell 2020-08
          %th.main__contents__table__head__cell 2020-09
          %th.main__contents__table__head__cell 2020-10
          %th.main__contents__table__head__cell 2020-11
          %th.main__contents__table__head__cell 2021-12
          %th.main__contents__table__head__cell 2022-01
          %th.main__contents__table__head__cell 2023-02
          %th.main__contents__table__head__cell 2024-03
        %tr.main__contents__table__record
          %td.main__contents__table__record__cell--sticky みずほ銀行
          %td.main__contents__table__record__cell--button 詳細
          %td.main__contents__table__record__cell 50,000
          %td.main__contents__table__record__cell 48,000
          %td.main__contents__table__record__cell 46,000
          %td.main__contents__table__record__cell 44,000
          %td.main__contents__table__record__cell 42,000
          %td.main__contents__table__record__cell 40,000
          %td.main__contents__table__record__cell 38,000
          %td.main__contents__table__record__cell 36,000
          %td.main__contents__table__record__cell 34,000
          %td.main__contents__table__record__cell 32,000
          %td.main__contents__table__record__cell 30,000
          %td.main__contents__table__record__cell 28,000
        %tr.main__contents__table__record#record_1
          %td.main__contents__table__record__cell--sticky みずほ銀行
          %td.main__contents__table__record__cell--button 詳細
          %td.main__contents__table__record__cell 50,000
          %td.main__contents__table__record__cell 48,000
          %td.main__contents__table__record__cell 46,000
          %td.main__contents__table__record__cell 44,000
          %td.main__contents__table__record__cell 42,000
          %td.main__contents__table__record__cell 40,000
          %td.main__contents__table__record__cell 38,000
          %td.main__contents__table__record__cell 36,000
          %td.main__contents__table__record__cell 34,000
          %td.main__contents__table__record__cell 32,000
          %td.main__contents__table__record__cell 30,000
          %td.main__contents__table__record__cell 28,000
        %tr.main__contents__table__record#record_1
          %td.main__contents__table__record__cell--sticky みずほ銀行
          %td.main__contents__table__record__cell--button 詳細
          %td.main__contents__table__record__cell 50,000
          %td.main__contents__table__record__cell 48,000
          %td.main__contents__table__record__cell 46,000
          %td.main__contents__table__record__cell 44,000
          %td.main__contents__table__record__cell 42,000
          %td.main__contents__table__record__cell 40,000
          %td.main__contents__table__record__cell 38,000
          %td.main__contents__table__record__cell 36,000
          %td.main__contents__table__record__cell 34,000
          %td.main__contents__table__record__cell 32,000
          %td.main__contents__table__record__cell 30,000
          %td.main__contents__table__record__cell 28,000
    

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DebtManagement
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield